# Generated by Django 4.1.7 on 2023-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DubicarsCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('kms', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
