# Generated by Django 4.1.7 on 2023-04-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_any',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('kms', models.IntegerField()),
                ('contact', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('regSpecs', models.CharField(max_length=255, null=True)),
                ('activeListings', models.IntegerField(null=True)),
                ('posted', models.CharField(max_length=25, null=True)),
                ('site', models.CharField(max_length=25, null=True)),
                ('active', models.BooleanField(default=True)),
                ('old_price', models.CharField(max_length=255, null=True)),
                ('listing_type', models.CharField(max_length=255, null=True)),
                ('listing_type_changed', models.IntegerField()),
                ('notified', models.BooleanField(default=False)),
                ('category_id_dubizzle', models.TextField(null=True)),
                ('post_created_at', models.IntegerField(default=1682335612.2899222)),
                ('activeForSite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='regSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('site', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('contact', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('activeListings', models.IntegerField()),
                ('site', models.CharField(max_length=255)),
            ],
        ),
    ]
