# Generated by Django 4.1.7 on 2023-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='id',
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car_any',
            name='post_created_at',
            field=models.IntegerField(default=1682336513.1629207),
        ),
    ]
