# Generated by Django 4.1.7 on 2023-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubizzleCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('kilometers', models.DecimalField(decimal_places=2, max_digits=9)),
                ('posted', models.DateTimeField()),
                ('active_listings_count', models.IntegerField()),
                ('reg_specs', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YallamotorCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('kms', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
