# Generated by Django 4.1.7 on 2023-02-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dubizzlecar_yallamotorcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubizzlecar',
            name='posted',
            field=models.CharField(max_length=25),
        ),
    ]
