# Generated by Django 4.1.7 on 2023-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_any_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_any',
            name='post_created_at',
            field=models.IntegerField(default=1682337328.2013774),
        ),
    ]
