# Generated by Django 4.1.7 on 2023-02-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dubizzlecar_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubicarscar',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dubicarscar',
            name='kms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dubizzlecar',
            name='active_listings_count',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dubizzlecar',
            name='kilometers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dubizzlecar',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dubizzlecar',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='yallamotorcar',
            name='kms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='yallamotorcar',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
