# Generated by Django 4.1.7 on 2023-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dubicarscar_phone_alter_dubicarscar_kms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubicarscar',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
