# Generated by Django 4.1.7 on 2023-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dubicarscar_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubizzlecar',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yallamotorcar',
            name='kms',
            field=models.IntegerField(),
        ),
    ]
