# Generated by Django 4.1.7 on 2023-04-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_test_alter_car_any_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_any',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car_any',
            name='post_created_at',
            field=models.IntegerField(default=1682338600.4289155),
        ),
    ]
