# Generated by Django 4.1.7 on 2023-02-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_dubicarscar_kms_alter_dubizzlecar_kilometers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubicarscar',
            name='activeListings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dubicarscar',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dubicarscar',
            name='regSpecs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dubicarscar',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
