# Generated by Django 4.1.7 on 2023-04-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_car_any_test_alter_car_any_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_any',
            name='test',
        ),
        migrations.AlterField(
            model_name='car_any',
            name='post_created_at',
            field=models.IntegerField(default=1682338617.8786428),
        ),
    ]
