# Generated by Django 4.1.7 on 2023-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dubicarscar_activelistings_dubicarscar_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yallamotorcar',
            name='activeListings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='yallamotorcar',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yallamotorcar',
            name='regSpecs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yallamotorcar',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
