# Generated by Django 4.1.7 on 2023-06-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_car_any_photo_alter_car_any_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_any',
            name='descriptionFaceBook',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car_any',
            name='post_created_at',
            field=models.IntegerField(default=1687027799.456667),
        ),
    ]
