# Generated by Django 4.1.7 on 2023-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_dubizzlecar_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('kms', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('year', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('regSpecs', models.CharField(max_length=255, null=True)),
                ('activeListings', models.IntegerField(null=True)),
                ('posted', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
