# Generated by Django 4.1.7 on 2023-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='site',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
