# Generated by Django 4.1.7 on 2023-02-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_car_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Car_any',
        ),
    ]
