# Generated by Django 4.1.7 on 2023-02-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_brands_alter_car_any_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands')),
            ],
        ),
    ]
