# Generated by Django 4.1.7 on 2023-03-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_regspecs_delete_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='regspecs',
            name='site',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='regspecs',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
