# Generated by Django 4.1.7 on 2023-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_regspecs_site_alter_regspecs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regspecs',
            name='site',
            field=models.TextField(max_length=127, null=True),
        ),
    ]
