# Generated by Django 4.1.7 on 2023-03-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_regspecs_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='regspecs',
            name='site',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
