# Generated by Django 4.1.7 on 2023-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_price_car_any_currentprice_car_any_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listers',
            fields=[
                ('id', models.CharField(max_length=127, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='car_any',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car_any',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
