# Generated by Django 4.1.7 on 2023-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_listers_car_any_new_car_any_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_any',
            name='id',
        ),
        migrations.AlterField(
            model_name='car_any',
            name='url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
