# Generated by Django 4.1.7 on 2023-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_car_any_id_alter_car_any_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_any',
            name='new',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='car_any',
            name='urgent',
            field=models.BooleanField(),
        ),
    ]
