# Generated by Django 4.1.7 on 2023-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_car_any_new_alter_car_any_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_any',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car_any',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
