# Generated by Django 4.1.7 on 2023-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_car_any_new_alter_car_any_urgent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_any',
            old_name='new',
            new_name='listing_type_changed',
        ),
        migrations.RenameField(
            model_name='car_any',
            old_name='currentPrice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='car_any',
            name='oldPrice',
        ),
        migrations.RemoveField(
            model_name='car_any',
            name='urgent',
        ),
        migrations.AddField(
            model_name='car_any',
            name='listing_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car_any',
            name='old_price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
