# Generated by Django 4.1.7 on 2023-03-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_new_car_any_listing_type_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_any',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
