# Generated by Django 4.1.7 on 2023-03-24 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_car_any_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSESubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
