# Generated by Django 4.1.7 on 2023-03-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_ssesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSESubscription',
        ),
    ]
