# Generated by Django 4.1.7 on 2023-03-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_car_any_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DubicarsCar',
        ),
        migrations.DeleteModel(
            name='DubizzleCar',
        ),
        migrations.DeleteModel(
            name='YallamotorCar',
        ),
        migrations.RenameField(
            model_name='car_any',
            old_name='new',
            new_name='notified',
        ),
        migrations.AddField(
            model_name='car_any',
            name='category_id_dubizzle',
            field=models.TextField(null=True),
        ),
    ]
